// Code generated by go generate; DO NOT EDIT.
// generated using files from resources directory
// DO NOT COMMIT this file
package system

func init() {
	SysInfo = Info{TPMMorphia: "0.0.7-SNAPSHOT", BuildNum: "UNDEF", GitSHA: "UNDEF", GOOS: "darwin", GOARCH: "arm64"}
}
