module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-morphia
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-morphia/examples/example6/entities
imports:
  - ./schema-beans.yml
entities:
  - document: true
    file-name: ./author.yml
  - file-name: ./book.yml
    package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-morphia/examples/example6/entities/book
  - file-name: ./address.yml

